/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as ChargesRouteImport } from './routes/charges'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CalculatorsTypeRouteImport } from './routes/calculators.$type'
import { Route as FundsCompareRouteImport } from './routes/funds.compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargesRoute = ChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsTypeRoute = CalculatorsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => CalculatorsRoute,
} as any)
const FundsCompareRoute = FundsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => FundsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/charges': typeof ChargesRoute
  '/compare': typeof CompareRoute
  '/funds': typeof FundsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommend': typeof RecommendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/$type': typeof CalculatorsTypeRoute
  '/funds/compare': typeof FundsCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/charges': typeof ChargesRoute
  '/compare': typeof CompareRoute
  '/funds': typeof FundsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommend': typeof RecommendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/$type': typeof CalculatorsTypeRoute
  '/funds/compare': typeof FundsCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/charges': typeof ChargesRoute
  '/compare': typeof CompareRoute
  '/funds': typeof FundsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommend': typeof RecommendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/$type': typeof CalculatorsTypeRoute
  '/funds/compare': typeof FundsCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculators'
    | '/charges'
    | '/compare'
    | '/funds'
    | '/privacy'
    | '/profile'
    | '/recommend'
    | '/sitemap.xml'
    | '/calculators/$type'
    | '/funds/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculators'
    | '/charges'
    | '/compare'
    | '/funds'
    | '/privacy'
    | '/profile'
    | '/recommend'
    | '/sitemap.xml'
    | '/calculators/$type'
    | '/funds/compare'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calculators'
    | '/charges'
    | '/compare'
    | '/funds'
    | '/privacy'
    | '/profile'
    | '/recommend'
    | '/sitemap.xml'
    | '/calculators/$type'
    | '/funds/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  ChargesRoute: typeof ChargesRoute
  CompareRoute: typeof CompareRoute
  FundsRoute: typeof FundsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecommendRoute: typeof RecommendRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charges': {
      id: '/charges'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/$type': {
      id: '/calculators/$type'
      path: '/$type'
      fullPath: '/calculators/$type'
      preLoaderRoute: typeof CalculatorsTypeRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/funds/compare': {
      id: '/funds/compare'
      path: '/compare'
      fullPath: '/funds/compare'
      preLoaderRoute: typeof FundsCompareRouteImport
      parentRoute: typeof FundsRoute
    }
  }
}

interface CalculatorsRouteChildren {
  CalculatorsTypeRoute: typeof CalculatorsTypeRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsTypeRoute: CalculatorsTypeRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

interface FundsRouteChildren {
  FundsCompareRoute: typeof FundsCompareRoute
}

const FundsRouteChildren: FundsRouteChildren = {
  FundsCompareRoute: FundsCompareRoute,
}

const FundsRouteWithChildren = FundsRoute._addFileChildren(FundsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  ChargesRoute: ChargesRoute,
  CompareRoute: CompareRoute,
  FundsRoute: FundsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecommendRoute: RecommendRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
